### ISSUE TITLE
Users should not link to copies of static libraries also installed on the system

### ISSUE THREAD

**Issue by mmuetzel** [siko1056/apa#1]
I'm not sure if the currently described installation process will be the one that should be used for a released version. So, please just close this issue if it isn't.

Anyway, if I correctly understand the installation procedure, the user is instructed copy some headers and libraries that are installed on the system and compile and link to those copies.
I don't think this is a good procedure.
If the system libraries change and the user does not copy them and recompile the package again, it is likely that there will be issues with clashing symbols.

Instead it would be better if the original files would be used for compilation and linking. The build rules should look for those headers and libraries (maybe using pkg-config).
In that case, the user would "only" need to type `pkg install path/to/package` again if those libraries ever updated.

**Comment by siko1056** [comment]
Thanks for the initial comments @mmuetzel, hadn't expected such early feedback :slightly_smiling_face: 

This apa package is indeed very experimental regarding the setup and tries to overcome many disadvantages I have seen with similar packages (e.g. biosig recently).

The package is expected to run on all commonly used Octave/Matlab setups.  I cannot rely on the user to provide the correct library in the latest version herself.  Same I do not want to beg the distributors of Octave and Matlab to keep up to date with their libraries.  Static linking seems to me the best option to achieve this and I bundle pre-compiled versions for the user convenience.  On macOS and Linux all could be compiled, but nobody likes a long setup time.

However, I noticed with Octaves' pkg another artificial limitation is in my way :sweat: 
```
>> pkg install https://github.com/gnu-octave/apa/releases/download/v0.1.0/apa-0.1.0.zip
error: bundles of packages are not allowed
```

Again thanks for the feedback and there will certainly be more changes to the current state :wink:

**Comment by mmuetzel** [comment]
I might not understand correctly. I don't know how distributing pre-compiled binaries would work.
I don't think it will be possible that Octave loads a library (.mex or .oct file) that is compiled/linked e.g. with an ABI incompatible libc (or other libraries). I don't think it makes a huge difference whether that library is statically linked or not...
Please correct me if that is wrong. Always happy to learn. :-)

**Comment by siko1056** [comment]
Hmm... maybe you can give the example of the README.md a shot.  It should install the package correctly in only a few seconds (compared to those very long installation times with pkg-config).

If you liked that approach, and hopefully did not experience any errors (which due to the freshness is likely to happen).  It could serve as a template for libraries of minor interest (not suitable to be distributed with mxe-octave), for example.

Regarding the ABI incompatibly, this might happen, but in rare cases for macOS and MS Windows (those are quite homogeneous environments).  For Linux and macOS user has the option to easily recompile the static libraries himself from the package itself and the mex-compilation will always favor those rebuild ones.

**Comment by mmuetzel** [comment]
At best, doing that would check if your build system is ABI compatible to my run system. (Which I assume it will be because you'll probably have used the compilers and libraries of a recently released Octave for Windows which I am using as well.)
If it was that easy, people wouldn't have found the need to invent docker, snap, ...
It's just not possible to use any odd library together with any other library/binary. They have to be compatible.
E.g., it will most likely not work to use a library that you compiled on a current Fedora with some software distributed with Debian oldstable or vice versa.

Edit: And even if they are compatible, it will likely cause problems if Octave was compiled and linked with a given version of e.g. libgomp but your library provides the same symbols but in a different version.

Welcome to DLL hell ;-)

**Comment by siko1056** [comment]
Yes, I am very sure, that my approach does not scale beyond one or two "simple" math libraries, like in my case.  But it is working, right? :slightly_smiling_face:   That is all that matters for me.  There will always be the setup that will not work for my assumptions, but same for pkg-config, you just have to wait ages to get the error message result :sweat_smile: 

But how else could you realize my project?  MS Windows is the root for the decision for the current layout.  On MS Windows you always have to provide the libraries in compiled form.  The typical MS Windows setup does not provide the tools (yet) to compile a library yourself.  Let alone explain those necessary steps to the average gifted Octave/Matlab user.  It must be provided in compiled form.

And to avoid the DLL hell or replacing Octaves' own libraries, static linking does the trick good enough, I think.

**Comment by mmuetzel** [comment]
Well, it looks like we disagree completely on this.
Octave for Windows includes everything to compile libraries. Afaict, you need to install a compiler to build .mex files in Matlab, too.
So, compiling the libraries should not be an issue.
In fact, you could just share the .mex files for Matlab on Windows IIUC. Why even bother to have them built on the user system?

It is a different question for Octave. But I think I wrote everything that I wanted to share already. This is your package and the decision how to distribute it is up to you.
I just don't think this is a good model and I hope that no one else will follow it in the future.

Edit: Just one other thing: Octave for Windows already installs gmp and mpfr that you could use.

**Comment by siko1056** [comment]
@mmuetzel , I really appreciate your concerns and without doubt you have great experience with Octave development and packages. You made your point crystal clear 😅

Two aspects need a small justification. First, a compiler alone does not enable running the whole GNU Autotools chain necessary to configure and build GMP and MPFR on the target system. Believe me or proof me wrong, it simply does not work on MS Windows for neither Octave nor Matlab 😓 Thus you have to bother unfortunately.

Regarding the pre-installed GMP and MPFR versions shipped with Octave. They are slightly outdated and I need a feature from the latest one. A typical development problem 🤠 A patch waits on Savannah for mxe developers to apply. However, changes don't float in before the next Octave release. And this dependency does not solve the Matlab issue 😓

Your final statement I find very harsh regarding my hard work on it. You must not like it, but please do not condemn it as evil antipattern neither 😓 There is no cheap/clean solution to my needs. Disregarding a working approach, that goes with 0 cost for Octave mxe development is inappropriate in my opinion. Octave can only benefit from it. As a great free interface for MPFR for Octave/Matlab is missing, it would attract users. All the responsibility is on me ☺️ 

There have been made far worse decisions in the past regarding packages, that were sold as "clean", but have many artificial limitations and Octave has to suffer from a little longer. As a result of those decisions: Octave package development is complicated and dead compared to other languages. As you know, I work on an improvement, but apa has priority for me now 🙂

**Comment by mmuetzel** [comment]
I'm sorry if I sounded too harsh. I very much appreciate the time and effort you put into the Octave ecosystem in general and especially Octave's packaging system.
I was worried that you would recommend that way of packaging dependencies into Octave packages to the community. I'm afraid that that would cause a lot of headache in the future (and possibly beef towards the community as a whole because "we" recommended that way to them).

I'm sorry if I haven't been clear before: Object files generated by different compilers (and possibly different versions of a compiler) are not compatible in general. That might be unfortunate. But that's just how it is.
IIUC, static libraries are basically just a collection of object files.
Albeit no official documentation, see e.g. https://github.com/modelica/ModelicaSpecification/issues/1316
To work around that, you could go the same way and distribute static libraries for all combinations of OS/compilers/versions/"bit-ness"/system libraries/... you'd like to support. But that would hardly make packaging easier than it currently is. I'd argue that it would make it even harder because the packager would need to be able to build all these different versions of the distributed binaries.
Alternatively, you could go the Matlab way and specify a limited set of combinations which your package is supporting (if that is not too limiting for your audience). If you are also targeting Matlab, you'd need to make sure to have sufficient overlap with the compilers/versions that they support in different versions of their software.

I still think the best way would be to build everything with the same compiler.

Is the update you are needing for MXE Octave the one from https://savannah.gnu.org/bugs/index.php?61008 ?
I'll try and have a look at it during the weekend. But like you probably know, jwe prefers to keep MXE Octave stable for dot-releases. So that update will most likely ride the default branch.

**Comment by mmuetzel** [comment]
Octave was recently included as an installable package in MSYS2. Since MSYS2 uses a rolling-release model (much like Arch Linux), it will most likely include more recent versions of dependencies than MXE Octave. You could advise Windows users of your package to install MSYS2 and use that version of Octave.
Similarly for macOS users and Homebrew.
For Linux users, it might be best to provide a docker/snap/flatpak/... package that includes the libraries in the version you'll need. Or that already includes the apa Octave package if you want to make it easy to be used.

Those options sound more reliable to me than distributing possibly incompatible static libraries.

**Comment by siko1056** [comment]
Thank you for all you comments so far.  As this issue has no solid foundation (a real installation problem), I would like you to turn this thread into a general discussion on Octave Discourse or you can start a meeting like I did once https://octave.discourse.group/t/online-developer-meeting-2020-11-10-the-future-of-octave-packages/349 and I am happy to attend and discuss with you and others about solutions to packaging problems.

**Comment by siko1056** [comment]
@mmuetzel It just took me 4 years to agree to you 😇 

Major game changer is that Matlab on MS Windows finally supports mingw and MSYS2 properly.  Thus there no need to please those users with the static library exercise, which indeed turns out to be hard to maintain, given that my time has been reduced a lot due to new work and private duties 🙂 

Also this change made me finally releasing this project.

Thank you again for all your valuable arguments here.
